In [1]:
n = 3
nombres = []
direcciones = []

for i in range(n):
    nombre = input("Nombre: ")
    direccion = input("Dirección: ")
    nombres.append(nombre)
    direcciones.append(direccion)

print(nombres)
print(direcciones)


Nombre: Mai
Dirección: calle 42 bis sir
Nombre: michel
Dirección: Carrera 42 norte


KeyboardInterrupt: Interrupted by user

In [4]:
import numpy as np
list = [10,20,30,40]
vctr = np.array(list)
vctr = np.array(list)
print("Vector creado")
print(vctr)

Vector creado
[10 20 30 40]


In [6]:
import numpy as np

fruits = ["Manzana", "Banana", "Naranja", "Fresa", "Mango"]

fruit_vector = np.array(fruits)

print("Vector creado para frutas:")
print(fruit_vector)


Vector creado para frutas:
['Manzana' 'Banana' 'Naranja' 'Fresa' 'Mango']


In [12]:
import numpy as np

Edades = ["18", "20", "22", "24", "26"]

Edades_vector = np.array(Edades)

print("Vector creado para edades:")
print(Edades_vector)


Vector creado para edades:
['Manzana' 'Banana' 'Naranja' 'Fresa' 'Mango']


In [28]:
import numpy as np
list = [["manzana"],
          ["Uvas"],
           ["Peras"],
                ["Fresas"]]
vctr = np.array(list)
print ("furtas")
print (vctr)




furtas
[['manzana']
 ['Uvas']
 ['Peras']
 ['Fresas']]


In [31]:
import numpy as np

list1 = [10, 20, 50, 60]
list2 = [1,2,3,4]
vctr1 = np.array(list1)
vctr2 = np.array(list2)

print ("Vector lista 1")
print (vctr1)
print ("Vector lista 2")
print (vctr2)

vctr_sub = vctr1 - vctr2
print ("La resta de vectores es", vctr_sub)


Vector lista 1
[10 20 50 60]
Vector lista 2
[1 2 3 4]
La resta de vectores es [ 9 18 47 56]
